default: PrefixCode.c Estruturas/tree.c Estruturas/heap.c Estruturas/tree.c
	gcc -Wall -g -std=c99 PrefixCode.c Estruturas/tree.c -o PrefixCode
	gcc -Wall -g -std=c99 Huffman.c Estruturas/heap.c Estruturas/tree.c -o Huffman 
	
