default: Estruturas/avl_tree.c Estruturas/list.c topology.c Estruturas/fifo.c algorithm.c
	gcc -Wall -g -std=c99 main.c Estruturas/avl_tree.c Estruturas/list.c Estruturas/fifo.c topology.c algorithm.c -o main
